package com.nagare.balkrishna.omkar.unmouse.GreenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nagare.balkrishna.omkar.unmouse.Entity.BluetoothInfo;

import com.nagare.balkrishna.omkar.unmouse.GreenDao.BluetoothInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bluetoothInfoDaoConfig;

    private final BluetoothInfoDao bluetoothInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bluetoothInfoDaoConfig = daoConfigMap.get(BluetoothInfoDao.class).clone();
        bluetoothInfoDaoConfig.initIdentityScope(type);

        bluetoothInfoDao = new BluetoothInfoDao(bluetoothInfoDaoConfig, this);

        registerDao(BluetoothInfo.class, bluetoothInfoDao);
    }
    
    public void clear() {
        bluetoothInfoDaoConfig.clearIdentityScope();
    }

    public BluetoothInfoDao getBluetoothInfoDao() {
        return bluetoothInfoDao;
    }

}
